# Dependencies
markdown:         kramdown
mathjax:          true

# Permalinks
permalink:        pretty

# Setup
title:            Epipolar
url:              https://itsuhane.github.io
baseurl:          /editorial-jekyll-theme

assets:
  styles:         /assets/styles
  fonts:          /assets/fonts
  scripts:        /assets/scripts
  images:         /assets/images

author:
  name:           itsuhane
  url:            https://github.com/itsuhane
  email:          itsuhane@gmail.com
  phone:          (000) 000-0000
  address:        Zhejiang Univ.
  address2:       Hangzhou, China

paginate:         5
