# Information
title:            Jekyll Editorial
url:              https://itsuhane.github.io
baseurl:          /editorial-jekyll-theme

assets:
  styles:         /assets/styles
  fonts:          /assets/fonts
  scripts:        /assets/scripts
  images:         /assets/images

author:
  name:           itsuhane
  url:            https://github.com/itsuhane
  email:          itsuhane@gmail.com
  phone:          (000) 000-0000
  address:        Zhejiang Univ.
  address2:       Hangzhou, China
  twitter:        twitter
  facebook:       facebook
  instagram:      instagram
  github:         github
  #weibo:

# Config for Menu
menu:
  hidden:         true

defaults:
  - scope:
      path:       ""
      type:       "posts"
    values:
      layout:     "post"
      comment:    "true" # <-- change to false if you want comments off by-default
      tags:       []

# Dependencies
markdown:         kramdown
mathjax:          true

# Permalinks
permalink:        pretty

# Pagination
paginate:         5
